# Build file for integration tests

py_test(
    name = "test_integration",
    srcs = ["test_integration.py"],
    data = ["//core:engine_main"],
    python_version = "PY3",
    srcs_version = "PY3",
)
